### ISSUE TITLE
Build beta with --release?

### ISSUE THREAD

**Issue by janpio** [CookieCookson/cordova-plugin-lifecycle#5]
> The beta variant is intended for when distributing your app over-the-air through services such as HockeyApp. Because of this it is recommended to pass through the release flag so the app is signed and runs with the release configuration.

Can you explain the thinking behind that? I always thought that building a beta version for internal testing shouldn't use `--release` so it can be debugged on device etc. - only when I actually plan to distribute something to end users you should use `--release`. Wrong?

**Comment by CookieCookson** [comment]
I imagine it depends on how you distribute your beta builds. I always work with remote teams so have to distribute OTA, therefore it needs to be signed with an Ad Hoc certificate (which has to be signed as release and cannot be debugged on device? Correct me if I'm wrong!). If you plan on distributing your beta build over USB to candidates, you shouldn't need the `--release` flag.

**Comment by janpio** [comment]
Ok Ad Hoc, so we're talking iOS here. This will get messy...

> I always work with remote teams so have to distribute OTA, therefore it needs to be signed with an Ad Hoc certificate (which has to be signed as release and cannot be debugged on device? Correct me if I'm wrong!)

Ad Hoc is release, and works like a release certificate - just has the same functionality of you being able to add devices and testing production push on it. Right?
Why do you have to use OTA because of the remote team?

(Sorry, I always confuse this stuff and have to re-learn it every time I come into contact with it)

**Comment by CookieCookson** [comment]
You're making me question why I am doing it this way now! 

I don't think you can distribute development builds on services like HockeyApp - to distribute these through services like HockeyApp they must be Ad Hoc builds. AFAIK you can only install development builds over USB (Through iTunes or xCode) and not over the web protocol (Mobile Safari). Things may be different again for services like TestFlight, but I have not used that service since Apple acquired them.

Hope this helps!

**Comment by janpio** [comment]
See, that's what happens every time I get into dev/production/Ad Hoc iOS stuff -1: 

Hmm, I have ~30 devices in my provisioning profile for the development certificate I use to build the beta version of my app that I give to my colleagues and customers via HockeyApp. This works fine and I thought was the "normal way to do it".

Do you also have to add the devices to the Ad Hoc prov profile? If so, it seems to me, that there is no real difference in using Ad Hoc profiles besides debugging...

**Comment by CookieCookson** [comment]
If it works - that sounds like a much better way of doing things (added USB support).

Yes, you have to add devices to the Ad Hoc profile in the same way, except the Ad Hoc uses production features rather than sandbox (e.g. Push!) and removes debugging access.

I'll give this a go myself and update the docs to be less specific on whether to use debug or release profiles.
